### ISSUE TITLE
🥅 [BACK] Todo List

### ISSUE THREAD

**Issue by Yonghyunc** [HeeJeYang/project_name#38]
### 주요 기능 (Back)

-  [ ] 사용자 맞춤 메뉴 추천 알고리즘 (사용자 최근 1주일 식단)
-  [ ] 메뉴 레시피 제공 및 검색 
-  [ ] 특정 메뉴 근처 맛집 정보 제공
-  [ ] 특정 메뉴 맘에 드는 레시피 찜
-  [ ] 재료 검색을 통한 활용 가능 레시피 탐색 
-  [ ] 사용자 최근 식단 CRUD 
-  [ ] 자유 게시판 CRUD
-  [ ] 자유 게시판 게시물 댓글 CRUD
-  [ ] 자유 게시판 게시물 추천
-  [ ] 인기 게시물 상단 노출 (추천수 기준, 실시간)
-  [ ] 로그인 
-  [ ] 로그아웃 
-  [ ] 회원가입 
-  [ ] 프로필 (유저 정보)

**Comment by Yonghyunc** [comment]
👍
